name: courseCI/CD.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
      working-directory: ./CourseManagementService
    - name: Run Linter
      run: npm run lint
      working-directory: ./CourseManagementService
    - name: Run npm audit
      run: npm audit
      working-directory: ./CourseManagementService  
    - name: Start the application in the background
      run: npm run start &
      working-directory: ./CourseManagementService
    - name: Wait for the application to start
      run: sleep 10
    - name: Kill the Node.js process
      run: kill $(jobs -p) || true
